from django.urls import path

from .views import (
    AddItemsToCourse,
    AnswerView,
    ApproachView,
    CharactersView,
    CharacterView,
    CharcterEqView,
    CourseItems,
    CourseView,
    GetCourseView,
    GetItemView,
    GetTheCoursesView,
    InitEqView,
    ItemsView,
    JoinCourseView,
    QuestionView,
    QuizView,
    QuizzesView,
)

urlpatterns = [
    path("course/", CourseView.as_view()),
    path("courses/", GetTheCoursesView.as_view()),
    path("course_by_id/", GetCourseView.as_view()),
    path("join_course/", JoinCourseView.as_view()),
    path("<int:course_id>/characters/", CharactersView.as_view()),
    path("<int:course_id>/character/", CharacterView.as_view()),
    path("items/", ItemsView.as_view()),
    path("item_by_id/", GetItemView.as_view()),
    path("<int:course_id>/shop/", CourseItems.as_view()),
    path("<int:course_id>/addItems/", AddItemsToCourse.as_view()),
    path("<int:course_id>/character/eq/", CharcterEqView.as_view()),
    path("quizzes/", QuizzesView.as_view()),
    path("questions/", QuestionView.as_view()),
    path("approaches/", ApproachView.as_view()),
    path("answers/", AnswerView.as_view()),
    path("<int:course_id>/quiz/", QuizView.as_view()),
    path("admin/admin/eq/", InitEqView.as_view()),
]
