# Generated by Django 3.2.7 on 2021-11-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210910_1234"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=120),
        ),
    ]
