# Generated by Django 3.2.2 on 2021-08-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="users",
        ),
    ]
