# Generated by Django 3.2.7 on 2021-11-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sell_price', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('eq_type', models.CharField(max_length=1)),
                ('stat', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor', to='courses.item'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='courses.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon', to='courses.item'),
        ),
        migrations.AddField(
            model_name='course',
            name='store_items',
            field=models.ManyToManyField(blank=True, related_name='store_items', to='courses.Item'),
        ),
    ]
