# Generated by Django 3.2.7 on 2021-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_answer_approach_question_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="a5",
        ),
        migrations.RemoveField(
            model_name="question",
            name="a6",
        ),
        migrations.AddField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[("o", "Open"), ("t", "Test"), ("e", "Event"), ("h", "Habit")],
                default="t",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="approach",
            name="duration_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="approach",
            name="end_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(default="1", max_length=1),
        ),
        migrations.AlterField(
            model_name="question",
            name="points",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="duration_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="end_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
