# Generated by Django 3.2.7 on 2021-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_alter_character_gold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("o", "Open"),
                    ("t", "Test"),
                    ("e", "Event"),
                    ("hp", "Habit_P"),
                    ("hn", "Habit_N"),
                    ("hm", "Habit_M"),
                ],
                default="t",
                max_length=2,
            ),
        ),
    ]
