# Generated by Django 3.2.7 on 2021-12-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_quiz_quiz_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user_answer",
            field=models.TextField(blank=True),
        ),
    ]
