# Generated by Django 3.2.7 on 2021-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_quiz_quiz_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(default="odp 1"),
        ),
    ]
