# Generated by Django 3.2.7 on 2021-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_alter_question_correct_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="approach",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
