# Generated by Django 3.2.7 on 2021-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_approach_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
