# Generated by Django 3.2.7 on 2021-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_answer_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approach",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
