# Generated by Django 3.2.7 on 2021-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_approach_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_answer',
            field=models.TextField(),
        ),
    ]
