name: Build Latex Document
on: 
    pull_request:
        branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Latex document
        uses: xu-cheng/latex-action@v2
        with:
            root_file: docs/main.tex
        env:
            TEXINPUTS: ".:./docs//:"
      - name: Add short_sha env property
        run: run: echo "short_sha=`echo ${{github.event.pull_request.head.sha}} | cut -c1-6`" >> $GITHUB_ENV
      - name: Upload Artifact 
        uses: actions/upload-artifact@v2
        with:
            name: docs-${{github.actor}}-${{github.event.number}}-${{env.short_sha}}
            path: main.pdf